### ISSUE TITLE
Sửa các lỗi trên thiết kế figma

### ISSUE THREAD

**Issue by tuanngoc0298** [tuanngoc0298/Nhom9#10]
- [x] Chữ lệch so với ảnh.
- [x] Kiểu chữ không hợp.
- [x] Các dòng thông tin lệch nhau

**Comment by A38857** [comment]
Đã xong: https://www.figma.com/file/4NUEAdkMRG6nrwkSeY8APx/Untitled?node-id=4%3A2&t=XdTQHeX1GXcWoyTV-0
