### ISSUE TITLE
Chức năng phát tất cả bài hát

### ISSUE THREAD

**Issue by tuanngoc0298** [tuanngoc0298/Nhom9#15]
Cần tạo một button để khi bấm vào có thể phát tất cả bài hát

**Comment by tuanngoc0298** [comment]
Đã hoàn thành!

![image](https://user-images.githubusercontent.com/75868787/222066700-4e2d9993-6c9e-4599-9a91-b6839d55c679.png)

**Comment by A38857** [comment]
![image](https://user-images.githubusercontent.com/75249611/222100267-e1add7e3-15b2-4301-9e07-1d44d85144ff.png)
Đã hoàn thành!
