### ISSUE TITLE
Tạo giao diện Album

### ISSUE THREAD

**Issue by tuanngoc0298** [tuanngoc0298/Nhom9#20]
Tạo giao diện Album có slide chuyển trang theo demo.
![image](https://user-images.githubusercontent.com/75868787/222093451-313993eb-dbbd-49a9-906c-81cdff47620b.png)

**Comment by A38857** [comment]
Đã hoàn thành!
![image](https://user-images.githubusercontent.com/75249611/222094460-1d49eb60-dc9b-4327-a25f-8e1265c72fa8.png)

**Comment by A38857** [comment]
![image](https://user-images.githubusercontent.com/75249611/222100097-1169eb4b-da0a-437b-861c-59d068d1a280.png)
Đã hoàn thành!
