### ISSUE TITLE
Tìm các bài hát xu hướng, thịnh hành

### ISSUE THREAD

**Issue by ThuanTH2** [tuanngoc0298/Nhom9#8]

**Comment by A38857** [comment]
1.	Ai chung tình được mãi
2.	Yêu Là Cưới - Bài hát của Đông Nhi
3.	Ước mơ của Mẹ - Bài hát của Văn Mai Hương
4.	Cô đơn dành cho ai
5.	Váy cưới karaoke 
6.	Nếu là anh
7.	Em luôn ở trong tâm trí của anh
8.	Hãy để anh yêu em lần nữa
9.	Dằm trong tim
10.	Thời gian sẽ trả lời
11.	Anh xa nhớ
12.	Cùng anh
13.	Quên cách yêu karaoke - Lương Bích Hữu
14.	Học cách đi một mình
15.	Em yêu anh karaoke hit - Lương Bích Hữu
16.	Thế nhé anh - Bài hát karaoke Trương Quỳnh Anh
17.	Ngày buồn nhất - Bảo Thy
