### ISSUE TITLE
Lập trình giao diện trang cá nhân

### ISSUE THREAD

**Issue by A38857** [tuanngoc0298/Nhom9#9]
-Lập trình giao diện trang cáo nhân theo thiết kế dưới đây:
https://www.figma.com/file/4NUEAdkMRG6nrwkSeY8APx/Untitled?node-id=4%3A2

**Comment by tuanngoc0298** [comment]
Đã hoàn thành
![image](https://user-images.githubusercontent.com/75868787/217730648-e0ef94df-f814-4d21-8638-2a338069b9b6.png)
